### ISSUE TITLE
How to get multi-view images (nadir/forward/ backward images)？

### ISSUE THREAD

**Issue by JonasZero** [lauraset/BuildingHeightModel#1]
I found that evaluating the pretrained model also requires tlc images.

**Comment by lauraset** [comment]
Yes. Tlc images are required for this multi-task model. 
We obtained the multi-view images from the data provider (http://www.cresda.com/EN）.
Unfortunately, this data is limited to use and cannot be released publicly due to the copyright. 
However, you can try the ISPRS dataset for a good start at the link https://www.isprs.org/data/zy-3-Berlin/Default.aspx.
